### ISSUE TITLE
Nifty problems when installing in Windows

### ISSUE THREAD

**Issue by jhennies** [constantinpape/elf#29]
Hi @constantinpape,

I am getting this error for a Windows installation of elf (The Linux equivalent is working fine):

```
(paintera-mc-workflow-env) X:\>python -c "import elf.segmentation.features"                                                                                                                    Traceback (most recent call last): 
  File "<string>", line 1, in <module> 
  File "C:\Users\hennies\anaconda3\envs\paintera-mc-workflow-env\lib\site-packages\elf\segmentation\features.py", line 6, in <module>
    import nifty.distributed as ndist
  File "C:\Users\hennies\anaconda3\envs\paintera-mc-workflow-env\lib\site-packages\nifty\distributed\__init__.py", line 1, in <module>
    from . import _distributed as __distributed 
ImportError: dynamic module does not define module export function (PyInit__distributed)
```

I tried installing with multiple versions of python and/or elf which does not fix the issue. An example environment that  gives the error above in Windows and works in Linux (at least same nifty, elf, and python version, for the rest I didn't check, I can post if relevant) was installed with:

```
conda create -n myenv -c cpape -c conda-forge elf python=3.7
```

And looks like this:

```
# Name                    Version                   Build  Channel
blosc                     1.21.0               h0e60522_0    conda-forge
boost                     1.74.0           py37h3b38789_3    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py37hcc03f2d_3    conda-forge
dask-core                 2021.3.0           pyhd8ed1ab_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
elf                       0.2.2             py_0_gabd9801    cpape
et_xmlfile                1.0.1                   py_1001    conda-forge
fftw                      3.3.9           nompi_hd3ad3c4_101    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
glpk                      4.65              h8ffe710_1003    conda-forge
h5py                      3.1.0           nompi_py37h19fda09_100    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
ilmbase                   2.5.5                h12d4b20_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge 
jdcal                     1.4.1                      py_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lemon                     1.3.1                h7f30438_3    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.75.0               hf1763fc_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
llvmlite                  0.36.0           py37habb0c8c_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge 
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge 
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge 
m2w64-gmp                 6.1.0                         2    conda-forge
 m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-base           3.3.4            py37h3379fd5_0    conda-forge 
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.5                        py_0    conda-forge 
nifty                     1.0.8            py37h80912f5_2    conda-forge
nose                      1.3.7                   py_1006    conda-forge
numba                     0.53.1           py37h4e635f9_0    conda-forge
numpy                     1.20.1           py37hd20adf4_0    conda-forge 
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openexr                   2.5.5                hab3b255_0    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
pandas                    1.2.3            py37h08fd248_0    conda-forge
pillow                    8.1.2            py37h96663a1_0    conda-forge 
pip                       21.0.1             pyhd8ed1ab_0    conda-forge 
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyreadline                2.1             py37h03978a9_1003    conda-forge 
python                    3.7.10          h7840368_100_cpython    conda-forge 
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge 
pywavelets                1.1.1            py37hda49f71_3    conda-forge
pyyaml                    5.4.1            py37hcc03f2d_0    conda-forge 
scikit-image              0.16.2           py37he350917_0    conda-forge
scikit-learn              0.24.1           py37heb15398_0    conda-forge
scipy                     1.6.1            py37h6db1a17_0    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
skan                      0.8                        py_1    conda-forge 
sqlite                    3.35.2               h8ffe710_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge  
tk                        8.6.10               h8ffe710_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge 
tornado                   6.1              py37hcc03f2d_1    conda-forge 
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge 
vc                        14.2                 hb210afc_4    conda-forge 
vigra                     1.11.1          py37h839d5b0_1023    conda-forge 
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge 
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge  
z5py                      2.0.9            py37h0392835_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge 
```

Any ideas?

**Comment by constantinpape** [comment]
Fundamentally this is caused by this: https://github.com/conda-forge/nifty-feedstock/pull/3
However, the `nifty.distributed` functionality is not used much my elf, so I check for this in the more recent versions, see https://github.com/constantinpape/elf/blob/master/elf/segmentation/features.py#L8-L11.

So you should be able to fix this issue by installing the latest elf version: 
`conda install "elf>=0.2.4"`

**Comment by constantinpape** [comment]
> conda create -n myenv -c cpape -c conda-forge elf python=3.7

Oh, and you should use conda-forge as the higher priority channel, i.e.
```
conda -c conda-forge -c cpape ...
```

(It shouldn't change much here though, I think I removed all conflicting packages from my channel).

**Comment by jhennies** [comment]
> Oh, and you should use conda-forge as the higher priority channel, i.e.

Yes, this indeed doesn't seem to make a difference here, but I'll keep it in mind

However this did make a huge difference and fixed the issue:

> ```conda install "elf>=0.2.4"```

Thanks a lot!
